python3: can't open file '/home/developer/Workspace_Projects/data_engineer_assignment/level_1/solution.py': [Errno 2] No such file or directory
python3: can't open file '/home/developer/Workspace_Projects/data_engineer_assignment/level_2/solution.py': [Errno 2] No such file or directory
mysql: [Warning] Using a password on the command line interface can be insecure.
site_name	oncology_rate
New York University Hospital	0.3448
Lisbon University Hospital	0.3452
site_name
Lyon Medical Center
New York University Hospital
Los Angeles
Lisbon University Hospital
Miami Health Institute
ERROR 1064 (42000) at line 20 in file: '/home/developer/Workspace_Projects/data_engineer_assignment/level_3/queries.sql': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '--run via this =>  mysql -u root -p inato_data < queries.sql' at line 1

[2025-10-27 19:12:01.712734] Starting automated pipeline...
[2025-10-27 19:12:01.740410] Running query.sql...
[2025-10-27 19:12:01.752603] Pipeline completed successfully!

python3: can't open file '/home/developer/Workspace_Projects/data_engineer_assignment/level_1/solution.py': [Errno 2] No such file or directory
python3: can't open file '/home/developer/Workspace_Projects/data_engineer_assignment/level_2/solution.py': [Errno 2] No such file or directory
mysql: [Warning] Using a password on the command line interface can be insecure.
site_name	oncology_rate
New York University Hospital	0.3448
Lisbon University Hospital	0.3452
site_name
Lyon Medical Center
New York University Hospital
Los Angeles
Lisbon University Hospital
Miami Health Institute
ERROR 1064 (42000) at line 20 in file: '/home/developer/Workspace_Projects/data_engineer_assignment/level_3/queries.sql': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '--run via this =>  mysql -u root -p inato_data < queries.sql' at line 1

[2025-10-27 19:13:02.036006] Starting automated pipeline...
[2025-10-27 19:13:02.063273] Running query.sql...
[2025-10-27 19:13:02.075079] Pipeline completed successfully!

python3: can't open file '/home/developer/Workspace_Projects/data_engineer_assignment/level_1/solution.py': [Errno 2] No such file or directory
python3: can't open file '/home/developer/Workspace_Projects/data_engineer_assignment/level_2/solution.py': [Errno 2] No such file or directory
mysql: [Warning] Using a password on the command line interface can be insecure.
site_name	oncology_rate
New York University Hospital	0.3448
Lisbon University Hospital	0.3452
site_name
Lyon Medical Center
New York University Hospital
Los Angeles
Lisbon University Hospital
Miami Health Institute
ERROR 1064 (42000) at line 20 in file: '/home/developer/Workspace_Projects/data_engineer_assignment/level_3/queries.sql': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '--run via this =>  mysql -u root -p inato_data < queries.sql' at line 1

[2025-10-27 19:14:01.356333] Starting automated pipeline...
[2025-10-27 19:14:01.383645] Running query.sql...
[2025-10-27 19:14:01.395483] Pipeline completed successfully!

python3: can't open file '/home/developer/Workspace_Projects/data_engineer_assignment/level_1/solution.py': [Errno 2] No such file or directory
python3: can't open file '/home/developer/Workspace_Projects/data_engineer_assignment/level_2/solution.py': [Errno 2] No such file or directory
mysql: [Warning] Using a password on the command line interface can be insecure.
site_name	oncology_rate
New York University Hospital	0.3448
Lisbon University Hospital	0.3452
site_name
Lyon Medical Center
New York University Hospital
Los Angeles
Lisbon University Hospital
Miami Health Institute
ERROR 1064 (42000) at line 20 in file: '/home/developer/Workspace_Projects/data_engineer_assignment/level_3/queries.sql': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '--run via this =>  mysql -u root -p inato_data < queries.sql' at line 1

[2025-10-27 19:15:01.676738] Starting automated pipeline...
[2025-10-27 19:15:01.704106] Running query.sql...
[2025-10-27 19:15:01.715868] Pipeline completed successfully!

python3: can't open file '/home/developer/Workspace_Projects/data_engineer_assignment/level_1/solution.py': [Errno 2] No such file or directory
python3: can't open file '/home/developer/Workspace_Projects/data_engineer_assignment/level_2/solution.py': [Errno 2] No such file or directory
mysql: [Warning] Using a password on the command line interface can be insecure.
site_name	oncology_rate
New York University Hospital	0.3448
Lisbon University Hospital	0.3452
site_name
Lyon Medical Center
New York University Hospital
Los Angeles
Lisbon University Hospital
Miami Health Institute
ERROR 1064 (42000) at line 20 in file: '/home/developer/Workspace_Projects/data_engineer_assignment/level_3/queries.sql': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '--run via this =>  mysql -u root -p inato_data < queries.sql' at line 1

[2025-10-27 19:16:01.955233] Starting automated pipeline...
[2025-10-27 19:16:01.982651] Running query.sql...
[2025-10-27 19:16:01.994792] Pipeline completed successfully!

python3: can't open file '/home/developer/Workspace_Projects/data_engineer_assignment/level_1/solution.py': [Errno 2] No such file or directory
python3: can't open file '/home/developer/Workspace_Projects/data_engineer_assignment/level_2/solution.py': [Errno 2] No such file or directory
mysql: [Warning] Using a password on the command line interface can be insecure.
site_name	oncology_rate
New York University Hospital	0.3448
Lisbon University Hospital	0.3452
site_name
Lyon Medical Center
New York University Hospital
Los Angeles
Lisbon University Hospital
Miami Health Institute
ERROR 1064 (42000) at line 20 in file: '/home/developer/Workspace_Projects/data_engineer_assignment/level_3/queries.sql': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '--run via this =>  mysql -u root -p inato_data < queries.sql' at line 1

[2025-10-27 19:17:02.266982] Starting automated pipeline...
[2025-10-27 19:17:02.294416] Running query.sql...
[2025-10-27 19:17:02.306322] Pipeline completed successfully!

Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 16
    def run_c
             ^
SyntaxError: expected '('
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 19
    log
SyntaxError: expected 'except' or 'finally' block
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
Traceback (most recent call last):
  File "/home/developer/Workspace_Projects/data_engineer_assignment/level_3/scheduler.py", line 10, in <module>
    print(f"\n[{datetime.now()}] Starting automated pipeline...")
                ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
[2025-10-27 19:54:30.342984] Starting automated pipeline...
[2025-10-27 19:54:30.475129] All new files converted to JSON
[2025-10-27 19:54:31.268669] All new data inserted successfully!
[2025-10-27 19:54:31.281816] SQL ERROR: Command '['mysql', 'inato_data', '-e', 'source /home/developer/Workspace_Projects/data_engineer_assignment/level_3/queries.sql']' returned non-zero exit status 1.
[2025-10-27 19:54:31.281885] Pipeline completed successfully!

[2025-10-27 19:55:18.498731] Starting automated pipeline...
[2025-10-27 19:55:18.620351] All new files converted to JSON
[2025-10-27 19:55:19.630622] All new data inserted successfully!
[2025-10-27 19:55:19.643870] Query.sql executed successfully
[2025-10-27 19:55:19.643932] Pipeline completed successfully!

